Add-Type -AssemblyName System.Drawing
$bmp = New-Object System.Drawing.Bitmap(192,192)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.Clear([System.Drawing.Color]::Black)
$font = New-Object System.Drawing.Font("Arial", 40)
$brush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::Aqua)
$g.DrawString("TG", $font, $brush, 50, 60)
$bmp.Save("d:\tinygames\public\icons\icon-192.png", [System.Drawing.Imaging.ImageFormat]::Png)
$bmp.Dispose()
$g.Dispose()

$bmp512 = New-Object System.Drawing.Bitmap(512,512)
$g512 = [System.Drawing.Graphics]::FromImage($bmp512)
$g512.Clear([System.Drawing.Color]::Black)
$font512 = New-Object System.Drawing.Font("Arial", 100)
$brush512 = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::DeepPink)
$g512.DrawString("TG", $font512, $brush512, 130, 160)
$bmp512.Save("d:\tinygames\public\icons\icon-512.png", [System.Drawing.Imaging.ImageFormat]::Png)
$bmp512.Dispose()
$g512.Dispose()
